name: dart_shp
description: An shapefile reader/writer for dart.
version: 1.1.1
homepage: https://www.hydrologis.com
repository: https://github.com/moovida/dart_shp
issue_tracker: https://github.com/moovida/dart_shp/issues

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  path: '>=1.8.3'
  #BSD
  dart_jts: '>=0.2.3'
  # BSD
  # timezone: ^0.5.7
  # BSD
  characters: '>=1.3.0'
  # BSD
  intl: '>=0.16.1'

  dart_hydrologis_utils: '>=0.8.1'
    # path: ../dart_hydrologis_utils/
    # git:
    #   url: https://github.com/moovida/dart_hydrologis_utils.git

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.2
